### PR TITLE
FEATURE #2: Plugin Manager

### PR DESCRIPTION
**Pull request by warut-vijit**
Adds a plugin manager system with priorities and persistent scripts. Will make a separate PR when adding filters

### CODE REVIEW

**Comment by wchill** [comment]
Preferably config.json files should be centralized. I suppose this is kind of dependent on #3.

**Comment by warut-vijit** [comment]
I get what you're saying, but the config fîles contain data specific to each plugin. If we combined them, the resulting file would need to be continually updated

**Comment by wchill** [comment]
For priority/persistence, that should be in the main config.

**Comment by modi95** [comment]
We're not using config.py anymore :)

**Comment by wchill** [comment]
@warut-vijit can you drop that last commit and rebase your commits against master instead?

**Comment by wchill** [comment]
Going to merge from the plugin-manager branch; closing for now.

**Pull request closed without merging**
